
#当前环境别名
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learn
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  #tomcat端口号
  port: 8001
  servlet:
    #context-path
    context-path: /examples
  #tomcat配置项
  tomcat:
    connection-timeout: 500
    max-connections: 256
    max-threads: 128


dd:
  name: "zhangsan"


pay:
  order-id: '1111111'
  pay-id: '1111111'
  amount: 10



